blank_issues_enabled: false
contact_links:
  - name: Documentation
    about: 'to read before reporting issues.'
    url: 'https://pikamug.gitbook.io/quests/'
  - name: Discord
    about: 'for quick answers to basic questions.'
    url: 'https://discordapp.com/invite/QdJAv2G7qg'
  - name: Development Builds
    about: 'to try after backing up your server.'
    url: 'https://ci.codemc.io/job/PikaMug/job/Quests/'
